# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useremployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Karyawan', verbose_name='Employee'),
        ),
    ]
