# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeBarang', models.CharField(max_length=15, verbose_name='KODE BARANG')),
                ('namaBarang', models.CharField(max_length=45, verbose_name='NAMA BARANG')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('keterangan', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Barang')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaSatuan', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Barang')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Satuan')),
            ],
        ),
        migrations.AddField(
            model_name='barangmasuk',
            name='satuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Satuan'),
        ),
        migrations.AddField(
            model_name='barang',
            name='satuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Satuan', verbose_name='SATUAN'),
        ),
    ]
