# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('loan', '0002_asetbarang_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjambarang',
            name='peminjam',
        ),
        migrations.AddField(
            model_name='pinjambarang',
            name='karyawan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Karyawan'),
            preserve_default=False,
        ),
    ]
