# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20170531_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjambarang',
            name='return_date',
        ),
    ]
