# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('loan', '0004_remove_pinjambarang_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengembalianBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.AsetBarang')),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Karyawan')),
            ],
        ),
    ]
