# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_pengembalianbarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjambarang',
            name='status',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
