# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pic/', verbose_name='Photo Profile'),
        ),
    ]
