# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_karyawan_prof_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Karyawan')),
            ],
        ),
    ]
