# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170612_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
