# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPerbaikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permintaanPerbaikan', models.TextField()),
                ('status', models.CharField(blank=True, max_length=15)),
                ('worked_at', models.DateTimeField(null=True)),
                ('finish_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finish_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finish_by', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
                ('worked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
