# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_pemakaianbarang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemakaianbarang',
            old_name='request',
            new_name='requestid',
        ),
    ]
