# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20170529_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPerbaikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(null=True)),
                ('perbaikan', models.ManyToManyField(to='maintenance.MasterPerbaikan')),
            ],
        ),
    ]
