# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20170530_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailperbaikan',
            name='request',
            field=models.ManyToManyField(to='maintenance.RequestPerbaikan'),
        ),
        migrations.RemoveField(
            model_name='detailperbaikan',
            name='perbaikan',
        ),
        migrations.AddField(
            model_name='detailperbaikan',
            name='perbaikan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maintenance.MasterPerbaikan'),
            preserve_default=False,
        ),
    ]
