# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_remove_detailperbaikan_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailperbaikan',
            name='request',
        ),
        migrations.AddField(
            model_name='detailperbaikan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
