# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_detailperbaikan_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailperbaikan',
            old_name='perbaikan',
            new_name='mperbaikan',
        ),
        migrations.RenameField(
            model_name='detailperbaikan',
            old_name='request',
            new_name='mrequest',
        ),
    ]
