# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_auto_20170530_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailperbaikan',
            old_name='mperbaikan',
            new_name='perbaikan',
        ),
        migrations.RenameField(
            model_name='detailperbaikan',
            old_name='mrequest',
            new_name='request',
        ),
    ]
